library(lattice)
library(MASS)
library(nlme)
data <- read.delim("../data/QABRPAKejiSalamander.txt", header=TRUE)
attach(data)
amphibians <- data.frame(Year = as.factor(year), Site = as.factor(site), Visit = as.factor(visit), Abundance = count)
detach(data)
rm(data)
xyplot(Abundance ~ Year | Site, data = amphibians, groups = Visit, type="b")
bwplot(Abundance ~ Year | Site, data = amphibians)

library(lme4)
amphibians.lm <- lmer(Abundance ~ 1 + (1|Site/Visit), amphibians, family=poisson)
amphibians.lm.year <- update(amphibians.lm, . ~ as.integer(Year) + .)
anova(amphibians.lm, amphibians.lm.year)